### ISSUE TITLE
Beta 2.29 alpha version and known issues tracking

### ISSUE THREAD

**Issue by reduf** [HasKha/GWToolboxpp#390]
Installation instructions:
1. Download [ToolboxBeta.zip](https://github.com/HasKha/GWToolboxpp/files/3980211/ToolboxBeta.zip)
2. Extract the `ToolboxBeta.zip` archive
3. Open your GWToolbox settings folder. You can find it at `C:\User\<user>\AppData\Local\GWToolboxpp`. You can also find it by typing `%LOCALAPPDATA%\GWToolboxpp` in your start menu or explorer path
4. Backup your toolbox settings! Copy and paste the following files somewhere else: GWToolbox.ini, builds.ini, herobuilds.ini, AgentColors.ini, interface.ini, Markers.ini, Theme.ini
5. **Replace** the GWToolbox.dll with the one you downloaded above
6. Launch GWToolbox.exe as usual. **It will only work if you have only one GW client running.** It may ask to update. Hit "Skip for now". You will want to accept the update once the message shows a new version.
7. Report bugs and feedback! Known issues will be listed below.

Known bugs:
* [X] Price check in Material window crash Guild Wars.
* [x] ~~Opening Xunlai from Info window crash Guild Wars.~~
* [x] Opening a template link will crash Guild Wars. 
* [ ] Tick-is-toggle is disabled.
* [x] "Maintain fov" try to maintain the fov, but patch was removed from GWCA.
* [x] Active pcons are not loaded from settings on restart anymore.

Launcher bugs:
* [x] Can't read character names, so launcher won't work with multiple GW copies open.

**Comment by MangelMaxime** [comment]
Hello, I am not sure what is described by 

>  Opening a template link will crash Guild Wars. (hint: disable that in settings)

If I try to open "Template code" from the game interface Guild Wars crash. I disabled from the toolbox settings:

- Game Settings --> Open web links from templates
- Game Settings --> Automatically change urls into build templates

But it still crashes. Is my bug a new one or the same described? If it's the same, am I disabling the correct settings?

**Comment by HasKha** [comment]
> Hello, I am not sure what is described by
> 
> > Opening a template link will crash Guild Wars. (hint: disable that in settings)
> 
> If I try to open "Template code" from the game interface Guild Wars crash. I disabled from the toolbox settings:
> 
> * Game Settings --> Open web links from templates
> * Game Settings --> Automatically change urls into build templates
> 
> But it still crashes. Is my bug a new one or the same described? If it's the same, am I disabling the correct settings?

Sorry, you're right, it will crash regardless. I didn't actually test that one.

**Comment by BearsMan** [comment]
whenever inside the game while running around anywhere or not moving ur character model or the screen itself tends to shake a little bit, however, I do not know if that is with Toolbox or not because without TB Open the character model doesn't tend to shake around

**Comment by BearsMan** [comment]
@3vcloud and I sorted the fov one

**Comment by MangelMaxime** [comment]
Before this beta version, the toolbox was memorizing the last pcons used between reload.

For example, if I had golden eggs active and relaunch the toolbox the golden eggs were still active. 

With the beta version after a relaunch it disabled all the pcons.

**Comment by smiley232** [comment]
https://github.com/HasKha/GWToolboxpp/commit/b86606d5b89a6363828356f3af7aa4bc98e4df9c ("Fix bug with loading active pcons")
just compiled it, it still does not activate the pcons set in the ini file (still all pcons are disabled).

**Comment by reduf** [comment]
Did you try to set some, close toolbox and restart it? Because, the previous version probably disable everything in `GWToolbox.ini`.

**Comment by smiley232** [comment]
yes, that's what i did. i also checked my GWToolbox.ini for the values in [pcons] and it seems
1) values get ignored at start of TB
2) pcons changes are not saved to ini (when i close TB or when i press "save now" in settings), the ini file stamp is modified though
3) other changes i do seem to work as intended (still changed after TB restart)

tyvm

**Comment by smiley232** [comment]
sry, my bad. i used the old dll for testing and did not notice. everything works as intended now, as far as i can see.
tyvm

**Comment by reduf** [comment]
Release was made and made a new issue for tick is toggle which can be found at #391.

**Comment by kazerniel** [comment]
I'm trying to launch the 2.29 version, but it gives the following error:

> GWToolbox++ - Clientside Error Dete...
> Please restart guild wars and try again.

**Comment by BearsMan** [comment]
@kazerniel u didnt put GWToolbox.dll in ur Toolbox directory folder 

instructions are here that I typed up: Toolboxpp/releases/tag/2.29_Release - use new GWTB_Launcher and set GWToolbox.dll in %localappdata%/GWToolboxpp (installation folder) for dll (type %localappdata% in start menu and look for GWToolboxpp folder and put dll in GWToolboxpp folder)

**Comment by kazerniel** [comment]
> instructions are here that I typed up: Toolboxpp/releases/tag/2.29_Release - use new GWTB_Launcher and set GWToolbox.dll in %localappdata%/GWToolboxpp (installation folder) for dll (type %localappdata% in start menu and look for GWToolboxpp folder and put dll in GWToolboxpp folder)

Thanks, I thought I did those steps, but apparently not. Which exe should I set to launch with GW1 after the patching?

**Comment by BearsMan** [comment]
@kazerniel set GWTB_Launcher.exe to set after patching
